# Generated by Django 5.2 on 2025-11-18 07:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.DurationField(
                        help_text="Enter duration in the HH:MM:SS format",
                        max_length=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(seconds=3600)
                            ),
                            django.core.validators.MaxValueValidator(
                                datetime.timedelta(seconds=14400)
                            ),
                        ],
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        help_text="Enter release date in format YYYY-MM-DD"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug will be auto generated",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("genres", models.ManyToManyField(to="movie.genre")),
                ("languages", models.ManyToManyField(to="movie.language")),
            ],
            options={
                "verbose_name_plural": "Movies",
            },
        ),
    ]
