# Generated by Django 5.2.8 on 2025-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug is an auto generated field",
                max_length=200,
                unique=True,
            ),
        ),
    ]
