# Generated by Django 5.2 on 2025-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_booking_bookingseat_slot_booking_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
