# Generated by Django 5.2.8 on 2025-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_slot_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Slug is an auto generated field", unique=True
            ),
        ),
    ]
